### ISSUE TITLE
typo

### ISSUE THREAD

**Issue by ThibaultGROUEIX** [Naereen/Objectif-Zero-Dechet-2018#5]
(qui impose aussi de recevoir le flux audio même si on ne le regarde pas8 !) -> (qui impose aussi de recevoir le flux video même si on ne le regarde pas8 !)
Super initiative, je suivrai ac attention !

**Comment by Naereen** [comment]
Merci ! J'ai écrit ça trop tard ;-)

**Comment by Naereen** [comment]
Il y a un flux RSS, si tu veux t'abonner : https://perso.crans.org/besson/zero-dechet/feeds/all.atom.xml
